/** @type {import('tailwindcss').Config} */
module.exports = {
  darkMode: 'class',
  content: [
    './app/**/*.{js,jsx,ts,tsx}',
    './components/**/*.{js,jsx,ts,tsx}',
    './pages/**/*.{js,jsx,ts,tsx}',
  ],
  theme: {
    extend: {
      colors: {
        // ── Obsidian Ethereal Design System ──
        'background':                  '#13131a',
        'on-background':               '#e4e1ec',
        'surface':                     '#13131a',
        'surface-dim':                 '#13131a',
        'surface-bright':              '#393840',
        'surface-container-lowest':    '#0e0e15',
        'surface-container-low':       '#1b1b22',
        'surface-container':           '#1f1f26',
        'surface-container-high':      '#2a2931',
        'surface-container-highest':   '#34343c',
        'on-surface':                  '#e4e1ec',
        'on-surface-variant':          '#ccc3d8',
        'inverse-surface':             '#e4e1ec',
        'inverse-on-surface':          '#303038',
        'outline':                     '#958da1',
        'outline-variant':             '#4a4455',
        'surface-tint':                '#d2bbff',
        'surface-variant':             '#34343c',
        // Primary — Violet
        'primary':                     '#d2bbff',
        'on-primary':                  '#3f008e',
        'primary-container':           '#7c3aed',
        'on-primary-container':        '#ede0ff',
        'inverse-primary':             '#732ee4',
        'primary-fixed':               '#eaddff',
        'primary-fixed-dim':           '#d2bbff',
        'on-primary-fixed':            '#25005a',
        'on-primary-fixed-variant':    '#5a00c6',
        // Secondary — Cyan
        'secondary':                   '#4cd7f6',
        'on-secondary':                '#003640',
        'secondary-container':         '#03b5d3',
        'on-secondary-container':      '#00424e',
        'secondary-fixed':             '#acedff',
        'secondary-fixed-dim':         '#4cd7f6',
        'on-secondary-fixed':          '#001f26',
        'on-secondary-fixed-variant':  '#004e5c',
        // Tertiary — Purple
        'tertiary':                    '#ddb7ff',
        'on-tertiary':                 '#490080',
        'tertiary-container':          '#8d36db',
        'on-tertiary-container':       '#f2dfff',
        'tertiary-fixed':              '#f0dbff',
        'tertiary-fixed-dim':          '#ddb7ff',
        'on-tertiary-fixed':           '#2c0051',
        'on-tertiary-fixed-variant':   '#6900b3',
        // Error
        'error':                       '#ffb4ab',
        'on-error':                    '#690005',
        'error-container':             '#93000a',
        'on-error-container':          '#ffdad6',
      },
      borderRadius: {
        DEFAULT: '0.25rem',
        lg:      '0.5rem',
        xl:      '0.75rem',
        '2xl':   '1rem',
        full:    '9999px',
      },
      spacing: {
        'gutter-desktop':           '24px',
        'margin-desktop':           '48px',
        'sidebar-width':            '280px',
        'sidebar-collapsed-width':  '80px',
        'margin-mobile':            '20px',
        'gutter-mobile':            '16px',
      },
      fontFamily: {
        sans:           ['Inter', 'sans-serif'],
        'headline-xl':  ['Inter'],
        'headline-lg':  ['Inter'],
        'headline-md':  ['Inter'],
        'body-lg':      ['Inter'],
        'body-md':      ['Inter'],
        'label-md':     ['Inter'],
        'label-sm':     ['Inter'],
      },
      fontSize: {
        'headline-xl':  ['48px', { lineHeight: '56px',  letterSpacing: '-0.02em', fontWeight: '700' }],
        'headline-lg':  ['32px', { lineHeight: '40px',  letterSpacing: '-0.01em', fontWeight: '700' }],
        'headline-md':  ['24px', { lineHeight: '32px',  fontWeight: '600' }],
        'body-lg':      ['18px', { lineHeight: '28px',  fontWeight: '400' }],
        'body-md':      ['16px', { lineHeight: '24px',  fontWeight: '400' }],
        'label-md':     ['14px', { lineHeight: '20px',  letterSpacing: '0.01em', fontWeight: '600' }],
        'label-sm':     ['12px', { lineHeight: '16px',  letterSpacing: '0.02em', fontWeight: '500' }],
      },
    },
  },
  plugins: [require('@tailwindcss/forms')],
};
